#!/usr/bin/env bash
#
# +-------------------------------------------------------------------------+
# | ~/.config/sxiv/exec/key-handler                                         |
# +-------------------------------------------------------------------------+
# | Copyright © 2021 Waldemar Schroeer                                      |
# |                  waldemar.schroeer(at)rz-amper.de                       |
# +-------------------------------------------------------------------------+

while read file
do
    case "$1" in
        "a")
            notify-send "Info" "$(pwd)"
            ;;
        "d")
            mv "$file" $HOME/Trash && notify-send "$file deleted."
            ;;
        "e")
            xterm -e sh -c "exiv2 pr -q -pa '$file' | less"
            ;;
        "k")
            mkdir affe
            mv "$file" affe
            ;;
        "i")
            notify-send "File information" "$(mediainfo "$file")"
            ;;
    esac
done

