#!/usr/bin/env bash
#
# +-------------------------------------------------------------------------+
# | xmerge                                                                  |
# +-------------------------------------------------------------------------+
# | Copyright © 2019 Waldemar Schroeer                                      |
# |                  waldemar.schroeer(at)rz-amper.de                       |
# +-------------------------------------------------------------------------+

# xrdb -merge -I$HOME ${HOME}/.Xresources
xrdb ~/.Xresources
xrdb -query
