#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | prepare.sh                                                                 |
# +----------------------------------------------------------------------------+
# | Copyright © 2019 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

# +----- Variables ------------------------------------------------------------+
export PATH=${PATH}:${HOME}/.local/bin
export XDG_CONFIG_DIRS=/etc/xdg
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_CONFIG_HOME=${HOME}/.config
export _JAVA_AWT_WM_NONREPARENTING=1
export OPENAI_API_KEY="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"

# +----- X11 related stuff ----------------------------------------------------+
if [[ -f ${HOME}/.Xresources ]]; then
    xrdb -merge -I${HOME} ${HOME}/.Xresources
fi

/bin/xset +fp ${HOME}/.local/share/fonts    # Prepend path to the current font path
/bin/xset fp rehash                         # Reset the font path to its current value
/bin/xset -b                                # Disable bell
/bin/xset s off
/bin/xset -dpms
/bin/xrandr --dpi 96

# +----- Start window manager -------------------------------------------------+
exec ${HOME}/.local/bin/dwm 2> ${HOME}/tmp/dwm.log
