#!/usr/bin/env bash
#
# +-------------------------------------------------------------------------+
# | dwm_media (wrapper to start mplayer)                                    |
# +-------------------------------------------------------------------------+
# | Copyright © 2019 Waldemar Schroeer                                      |
# |                  waldemar.schroeer(at)rz-amper.de                       |
# +-------------------------------------------------------------------------+

mplayer=/bin/mplayer
mpv=/bin/mpv
st=~/.local/bin/st
url=$1
antwoord="$( printf "Bayern 2\nBayern 3\nBayern 5\nDEFJAY\nMDR Aktuell\nMDR Jump\nMDR Jump in the Mix\nZDF\nZDF neo\nZDF info\nIPCam cam1 (HD)\nIPCam cam1 (SD)\n" | dmenu "$@" )"

case ${antwoord} in
    "Bayern 2")
    ${st} -c "Krasses Radio" -g 50X5 -e ${mplayer} -msgcolor http://br-br2-sued.cast.addradio.de/br/br2/sued/mp3/mid &
    ;;
    "Bayern 3")
    ${st} -c "Krasses Radio" -g 50X5 -e ${mplayer} -msgcolor http://br-br3-live.cast.addradio.de/br/br3/live/mp3/mid &
    ;;
    "Bayern 5")
    ${st} -c "Krasses Radio" -g 50X5 -e ${mplayer} -msgcolor http://br-b5aktuell-live.cast.addradio.de/br/b5aktuell/live/mp3/mid &
    ;;
    "DEFJAY")
    ${st} -c "Krasses Radio" -g 50X5 -e ${mplayer} -msgcolor http://sc1.netstreamer.net:8040 &
    ;;
    "MDR Aktuell")
    ${st} -c "Krasses Radio" -g 50X5 -e ${mplayer} -msgcolor -playlist http://avw.mdr.de/streams/284340-0_mp3_high.m3u
    ;;
    "MDR Jump")
    ${st} -c "Krasses Radio" -g 50X5 -e ${mplayer} -msgcolor -playlist http://avw.mdr.de/streams/284320-0_mp3_high.m3u
    ;;
    "MDR Jump in the Mix")
    ${st} -c "Krasses Radio" -g 50X5 -e ${mplayer} -msgcolor -playlist http://avw.mdr.de/streams/284321-2_mp3_high.m3u
    ;;
    "ZDF")
    ${mpv} https://zdf-hls-15.akamaized.net/hls/live/2016498/de/high/master.m3u8 &
    ;;
    "ZDF neo")
    ${mpv} https://zdf-hls-16.akamaized.net/hls/live/2016499/de/high/master.m3u8 &
    ;;
    "ZDF info")
    ${mpv} https://zdf-hls-17.akamaized.net/hls/live/2016500/de/high/master.m3u8 &
    ;;
    "IPCam cam1 (HD)")
    ${mpv} rtsp://cam1.domain.de:554/1 &
    ;;
    "IPCam cam1 (SD)")
    ${mpv} rtsp://cam1.domain.de:554/2 &
    ;;

esac


exit 0 
