#!/bin/sh
#
# +-------------------------------------------------------------------------+
# | .xinitrc                                                                |
# +-------------------------------------------------------------------------+
# | Copyright (C) 2019 Waldemar Schroeer                                    |
# |                    lassmichinruhe@rz-amper.de                           |
# +-------------------------------------------------------------------------+

# General stuff
# ---------------------------------------------------------------------------
PATH=$PATH:~/.local/bin

export XDG_CONFIG_DIRS=/etc/xdg
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache
export XDG_CONFIG_HOME=$HOME/.config

# X11 related stuff
# ---------------------------------------------------------------------------
[[ -f ${HOME}/.Xresources ]] && xrdb -merge -I$HOME ${HOME}/.Xresources
# /bin/xsetroot -fg black -bg white -bitmap /usr/include/X11/bitmaps/root_weave
# /bin/xrandr --output Virtual-1 --mode 1912x980
# /bin/xrandr --output Virtual-1 --mode 1920x1080
# /bin/xrandr --output Virtual-1 --mode 1440x900
# /bin/xrandr --output DP-3 --rotate left

# /bin/xset +fp ${HOME}/.local/share/fonts
# /bin/xset fp rehash
# /bin/xset -b # disable bell
/bin/xset s off
/bin/xset -dpms
/bin/xrandr --dpi 96

# Start window manager
# ---------------------------------------------------------------------------
exec ${HOME}/.local/bin/dwm 2> ${HOME}/tmp/dwm.log
