#!/usr/bin/env bash
#
# +-------------------------------------------------------------------------+
# | ~/.local/bin/dwm-brightness                                             |
# +-------------------------------------------------------------------------+
# | Copyright © 2022 Waldemar Schroeer                                      |
# |                  waldemar.schroeer(at)rz-amper.de                       |
# +-------------------------------------------------------------------------+

if [ $# -ne 1 ]; then
    printf "usage: dwm-brightness ( up|down )\n\n"
    exit 1
fi

if [ $1 == "up" ]; then
    light -A 5
elif [ $1 == "down" ]; then
    light -U 5
fi

exit

