#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ~/.local/bin/dwm-statuscmd                                                 |
# +----------------------------------------------------------------------------+
# |       Usage: ---                                                           |
# | Description: dwm status command script                                     |
# |    Requires: ---                                                           |
# |       Notes: ---                                                           |
# |      Author: Waldemar Schroeer                                             |
# |     Company: Rechenzentrum Amper                                           |
# |     Version: 1                                                             |
# |     Created: 28.10.2024                                                    |
# |    Revision: ---                                                           |
# |                                                                            |
# | Copyright © 2022 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

# +----- Variables ------------------------------------------------------------+
# application="dwm-statuscmd"
hints="string:x-canonical-private-synchronous:calendar"
tmp=${XDG_RUNTIME_DIR:-/tmp}/"$UID"_calendar_notification_month

# +----- Main -----------------------------------------------------------------+

send_errormsg(){
    urgency="critical"
    summary="Error"
    body="Take a closer look at your options. Something's wrong\n\nYour Options: ${1}; ${2};"
    send_notification "${summary}" "${body}" "" "${urgency}" "string:x-dunst-stack-tag:${RANDOM}"
    # dunstify -a "${application}" "Error" "Take a closer look at your options. Something's wrong.\n\nYour Options: ${1}; ${2};"
}

send_notification(){
    dunstify -a "${3:-dwm-statuscmd}" -u "${4:-normal}" -h "${5:-string:x-dunst-stack-tag:Status}" "${1}" "${2}"

}

get_interfaces_info() {
    # Get all interfaces except loopback
    for interface in $(ip -o link show | awk -F': ' '{print $2}' | grep -v '^lo$'); do
        # Get IP address from interface
        ip_info=$(ip -o -4 addr show "$interface" 2>/dev/null | awk '{print $4}')

        # Check if interface has IP address
        if [ -n "$ip_info" ]; then
            ip_address=${ip_info%/*}
            netmask=$(ipcalc -m "$ip_info" | awk -F'=' '{print $2}')
            # Get Speed and Duplex
            ethtool_output=$(ethtool "$interface" 2>/dev/null)
            speed=$(echo "$ethtool_output" | grep "Speed:" | awk '{print $2}')
            duplex=$(echo "$ethtool_output" | grep "Duplex:" | awk '{print $2}')
            
            # Fallback, falls Informationen nicht verfügbar sind
            speed=${speed:-"Unknown"}
            duplex=${duplex:-"Unknown"}

            # Print interface informations
            echo " "
            echo "Interface Name: $interface"
            echo "    IP Address: $ip_address"
            echo "       IP Mask: $netmask"
            echo "         Speed: $speed"
            echo "        Duplex: $duplex"
        fi
    done
}

if [[ "${#}" != "2" ]]; then
    send_errormsg ${1} ${2}
    exit 1
fi

# First option is given by the clicked selection
case ${1} in
    1)
        # Second option is the mouse button 1:Left, 2:Middle, 3:Right
        case ${2} in
            1)
                summary="Power Options"
                body="Nummer: 1; ${2}"
                ;;
            2)
                summary="Power Options"
                body="Nummer: 1; ${2}"
                ;;
            3)
                summary="Power Options"
                body="Nummer: 1; ${2}"
                ;;
            *)
                send_errormsg "${1}" "${2}"
                exit 1
        esac
        send_notification "${summary}" "${body}" "affe"
        ;;
    2)
        case ${2} in
            1)
                dwm-volumectrl up
                ;;
            2)
                dwm-volumectrl mute
                ;;
            3)
                dwm-volumectrl down
                ;;
            *)
                send_errormsg "${1}" "${2}"
                exit 1
        esac
        ;;
    3)
        case ${2} in
            1)
                send_notification "IP Addresses" "$(get_interfaces_info)"
                ;;
            2)
                dwm-volumectrl mute
                ;;
            3)
                dwm-volumectrl down
                ;;
            *)
                send_errormsg "${1}" "${2}"
                exit 1
        esac
        ;;
    4)
        summary="Sensors Information"
        body="$(sensors)"
        send_notification "${summary}" "${body}" "sensors"
        ;;
    5)
        case ${2} in
            1)
                summary="top"
                body="$(top -b -n 1 | head -20)"
                ;;
            2)
                summary="CPU statistics and input/output statistics"
                body="$(iostat -p ALL -k -N)"
                ;;
            3)
                summary="CPU Information"
                body="No Information yet."
                ;;
            *)
                send_errormsg "${1}" "${2}"
                exit 1
        esac
        send_notification "${summary}" "${body}" "CPU"
        ;;
    6)
        case ${2} in
            1)
                summary="Free and Used Memory"
                body="$(free --human --lohi --committed)"
                ;;
            2)
                summary="CPU statistics and input/output statistics"
                body="$(iostat -p ALL -k -N)"
                ;;
            *)
                send_errormsg "${1}" "${2}"
                exit 1
        esac
        send_notification "${summary}" "${body}" "Memory"
        ;;
    7)
        send_notification "Not in use." "You may come up with a new idea."
        ;;
    8)
        send_notification "Not in use." "You may come up with a new idea."
        ;;
    9)
        touch "${tmp}"
        today=$(date '+%-d')
        footer="\n<i>       ~ calendar</i> 󰸗 "
        diff=$(<"${tmp}")
        case ${2} in
            1) diff=0;;
            2) diff=$((diff+1));;
            3) diff=$((diff-1));;
            *)
                send_errormsg "${1}" "${2}"
                exit 1
                ;;
        esac
        echo "${diff}" > "${tmp}"
        if [[ "${diff}" -ge 0 ]]; then
            header=$(cal "+${diff} months" | head -n1)
            body=$(cal "+${diff} months" | tail -n7 | sed -z "s|${today}|<u><b>${today}</b></u>|1")
        else
            header=$(cal "$((-diff)) months ago" | head -n1)
            body=$(cal "$((-diff)) months ago" | tail -n7 | sed -z "s|${today}|<u><b>${today}</b></u>|1")
        fi
        echo "$((-diff)) months"
        send_notification "${header}" "${body}${footer}" "dwm-calendar"
        ;;
    *)
        send_errormsg "${1}" "${2}"
        ;;
esac

# +----- End ------------------------------------------------------------------+
exit 0

