#!/bin/sh
#
# +-------------------------------------------------------------------------+
# | slock-wrapper                                                           |
# +-------------------------------------------------------------------------+
# | Copyright © 2020 Waldemar Schroeer                                      |
# |                  waldemar.schroeer(at)rz-amper.de                       |
# +-------------------------------------------------------------------------+

# ${HOME}/.local/bin/slock -m "$(/bin/cowsay "$(/bin/fortune -a drugs)")" & 2>/dev/null

${HOME}/.local/bin/slock -m "$(/bin/cat ~/.slocktext)" & 2>/dev/null
