language: c
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libx11-dev
      - libxt-dev
      - libimlib2-dev
      - libxinerama-dev
      - libjpeg-progs
      - libtest-command-perl
      - libtest-simple-perl
      - libexif-dev
      - libexif12
script:
  - make
  - make test
compiler:
  - clang
  - gcc
env:
  - default=1
  - app=1
  - curl=0
  - exif=1
  - help=1
  - stat64=1
  - verscmp=0
  - xinerama=0
  - inotify=1
